packages/utils/src/WithLoader.tsx
syndesis/src/modules/connections/pages/ConnectionsPage.tsx
syndesis/src/modules/connections/pages/ConnectorsPage.tsx
syndesis/src/modules/dashboard/pages/DashboardPage.tsx
syndesis/src/modules/integrations/pages/IntegrationsPage.tsx

Fixes some bugs introduced with #24

Fix wrong behaviour of the WithLoader component

---

README.md

Adds i18n instructions to the readme

---

packages/ui/.storybook/addons.js
packages/ui/src/Customizations/CustomizationsApiConnectorDetail.tsx
packages/ui/src/Customizations/CustomizationsExtensionDetail.tsx
packages/ui/src/Customizations/CustomizationsExtensionImport.tsx
packages/ui/src/Customizations/CustomizationsExtensionListItem.tsx
packages/ui/src/Customizations/CustomizationsExtensionListView.tsx
packages/ui/src/Customizations/index.ts
packages/ui/stories/Customizations/CustomizationsApiConnectorDetail.stories.tsx
packages/ui/stories/Customizations/CustomizationsExtensionDetail.stories.tsx
packages/ui/stories/Customizations/CustomizationsExtensionImport.stories.tsx
packages/ui/stories/Customizations/CustomizationsExtensionListItem.stories.tsx
packages/ui/stories/Customizations/CustomizationsExtensionListView.stories.tsx

- registered addon-links to addons.js
- switched to using patternfly-react list components (most of which wrap bootstrap react components)
- added tooltips to CustomizationsApiConnectorListView
- updates to CustomizationsApiConnectorListItem and CustomizationsApiConnectorListView stories
- added details button and button tooltips to CustomizationsApiConnectorListItem
- added placeholder for CustomizationsApiConnectorDetail component
- added placeholder for CustomizationsExtensionDetail component
- added placeholder for CustomizationsExtensionImport component
- added CustomizationsExtensionListItem component
- added CustomizationsExtensionListView component
- added placeholder for CustomizationsApiConnectorDetail stories
- added placeholder for CustomizationsExtensionDetail stories
- added …

More work on issue 41 Customization: API Client Connectors page layout

---

packages/auto-form/src/widgets/FormTextAreaComponent.tsx
packages/auto-form/stories/FormTextAreaComponent.stories.tsx

This PR adds the PF3 textarea and a corresponding storybook.

feat(textarea): add pf3 textarea and storybook

---

packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/makeResolver.ts
syndesis/src/modules/connections/ConnectionsApp.tsx
syndesis/src/modules/connections/containers/ConnectionsWithToolbar.tsx
syndesis/src/modules/connections/index.tsx
syndesis/src/modules/connections/pages/ConnectionsPage.tsx
syndesis/src/modules/connections/pages/ConnectorFormPage.tsx
syndesis/src/modules/connections/pages/ConnectorsPage.tsx
syndesis/src/modules/connections/resolvers.ts
syndesis/src/modules/connections/routes.ts
syndesis/src/modules/dashboard/pages/DashboardPage.tsx
syndesis/src/modules/integrations/resolvers.ts
syndesis/src/modules/resolvers.ts
yarn.lock

These are the changes done during the live share session, plus a little bit of refactoring and cleanup.

feat: upgrade the connections module to use the routes/resolvers pattern.

---

packages/auto-form/src/AutoForm.tsx
packages/auto-form/src/FormBuilder.tsx
packages/auto-form/src/models.ts
packages/auto-form/src/widgets/FormCheckboxComponent.tsx
packages/auto-form/src/widgets/FormHiddenComponent.tsx
packages/auto-form/src/widgets/FormInputComponent.tsx
packages/auto-form/src/widgets/FormSelectComponent.tsx
packages/auto-form/src/widgets/FormTextAreaComponent.tsx
packages/auto-form/src/widgets/helpers.ts
packages/auto-form/tests/AutoForm.spec.tsx
packages/auto-form/tests/FormCheckboxComponent.spec.tsx
packages/auto-form/tests/FormInputComponent.spec.tsx
packages/auto-form/tests/FormSelectComponent.spec.tsx
packages/auto-form/tests/FormTextAreaComponent.spec.tsx
packages/models/src/extra.d.ts

bugfix(autoform): properly handle required fields

---

packages/ui/stories/Data/Virtualizations/VirtListView.stories.tsx

fixes issue with storyboook build from previous commit

fix storybook build issue

---

packages/auto-form/yalc.lock

Merged this file in error. Reference: https://github.com/syndesisio/syndesis-react-poc/pull/103

Rm yalc.lock

---

packages/ui/src/Layout/ButtonLink.tsx
packages/ui/stories/Layout/ButtonLink.stories.tsx

Fixes minor issue with ButtonLink.  The ButtonLink would not disable when href was set.  Fixed condition and added a ButtonLink story for testing.

Fix issue with ButtonLink

---

app/ui-react/packages/ui/package.json
app/ui-react/packages/ui/src/Integration/IntegrationDetailInfo.tsx
app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
app/ui-react/packages/ui/src/Shared/Notifications.tsx
app/ui-react/packages/ui/src/Shared/index.ts
app/ui-react/packages/ui/stories/Shared/DndFileChooser.stories.tsx
app/ui-react/syndesis/src/app/App.tsx
app/ui-react/syndesis/src/app/AppContext.tsx
app/ui-react/syndesis/src/app/__mocks__/App.tsx
app/ui-react/syndesis/src/modules/customizations/pages/ExtensionImportPage.tsx
app/ui-react/yarn.lock

This PR adds a wrapper Notifications module to the `@syndesis/ui` pkg. It also adds a new `pushNotification` capability in an app-wide context.
The DndFileChooser and ExtensionImportPage now use the new way of launching a notification.

feat(notifications): add notifications module

---

tools/bin/commands/ui

feat: add react support to 'syndesis ui'

---

app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx

Fixes issue with previous commit.  It should have been rebased after dialog PR was merged.

fix issue with dialog usage

---

app/ui-react/packages/api/package.json
app/ui-react/packages/api/src/WithIntegrationHelpers.tsx
app/ui-react/packages/api/src/constants.ts
app/ui-react/packages/models/src/extra.d.ts
app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
app/ui-react/yarn.lock

feat: connect start/stop/delete/export menu items to API

---

app/ui-react/packages/ui/stories/Shared/ConfirmationDialog.stories.tsx
app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx

fix: suppress confirmation dialog related warnings, also add a story for the no-icon version;

---

app/ui-react/doc/index.html

going through my laundry list :-)
This one's good because eventually I need to get more auto-form examples put together.

chore: update storybook link to point to the auto-form package

---

app/ui-react/packages/api/src/WithIntegrationHelpers.tsx
app/ui-react/packages/ui/src/Integration/Import/ImportPageUI.tsx
app/ui-react/packages/ui/src/Integration/Import/index.ts
app/ui-react/packages/ui/src/Integration/index.ts
app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
app/ui-react/packages/ui/src/index.ts
app/ui-react/packages/ui/stories/Integration/Import/ImportPageUI.stories.tsx
app/ui-react/syndesis/src/modules/integrations/index.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
app/ui-react/syndesis/src/modules/integrations/pages/import/ImportPage.tsx
app/ui-react/syndesis/src/modules/integrations/pages/import/index.ts
app/ui-react/syndesis/src/modules/integrations/pages/index.ts
app/ui-react/syndesis/src/modules/integrations/routes.ts

fixes #167
Also adds support for a list of success/error messages to the dnd widget there.

feat: implement import integration page

---

app/ui-react/packages/auto-form/package.json
app/ui-react/packages/auto-form/src/FormBuilder.tsx
app/ui-react/packages/auto-form/src/models.ts
app/ui-react/packages/auto-form/src/widgets/FormCheckboxComponent.tsx
app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
app/ui-react/packages/auto-form/src/widgets/FormHiddenComponent.tsx
app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx
app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx
app/ui-react/packages/auto-form/src/widgets/index.ts
app/ui-react/packages/auto-form/stories/KitchenSink.stories.tsx
app/ui-react/packages/auto-form/stories/SimpleExamples.stories.tsx
app/ui-react/packages/auto-form/stories/StoryWrapper.component.tsx
app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
app/ui-react/syndesis/src/modules/integrations/pages/create/configure/main/SaveIntegrationPage.tsx
app/ui-react/syndesis/src/modules/integrations/pages/integration/edit/main/SaveIntegrationPage.tsx
app/ui-react/syndesis/src/modules/integrations/shared/WithConfigurationForm.tsx

fixes #176
Also adds some groundwork for other auto-form improvements and a bunch of simpler, easier to look at storybooks.

feat: decouple auto-form from syndesis model

---

app/ui-react/packages/api/src/WithIntegrationHelpers.tsx
app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json

fixes #148
Ready for review.
Am feeling like we could refactor out all the actions into a separate component along with their dialogs, but I can't decide if that'd be worthwhile or not.  I'd do it later anyways, there's other things to get done.

feat: show notifications for start/stop/delete integration actions

---

app/ui-react/packages/api/src/WithEnvironments.tsx
app/ui-react/syndesis/src/modules/integrations/pages/cicd/ManageCiCdPage.tsx

fixes #183
@mdrillin FYI, I extended IFetchState with my type and added the read operation, then I'm calling that read operation when the call completes, this will then trigger re-rendering the list.  Hope that helps!

fix: force a fetch after performing a server call for environments

---

app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
app/ui-react/syndesis/src/modules/data/pages/VirtualizationRelationshipPage.tsx
app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx

- adds breadcrumbs to all of the view pages

Adds breadcrumbs to view pages

---

app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx
app/ui-react/syndesis/src/modules/data/pages/views/SelectViewsPage.tsx
app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx

- Resolves minor issue with SelectViewsPage - needed to supply the idPattern so that only the correct view states were considered.
- now including the serviceVdbName in WithVirtualizationsHelpers.createVirutalization function
- rename function in ViewInfosContent

TTOOLS-617 Resolve issue with view update status

---

app/ui-react/packages/api/src/WithServerEvents.tsx
app/ui-react/packages/ui/src/Layout/AppLayout.tsx
app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
app/ui-react/packages/ui/tests/AppLayout.spec.tsx
app/ui-react/packages/utils/src/WithLoader.tsx
app/ui-react/syndesis/src/app/App.tsx
app/ui-react/syndesis/src/app/AppContext.tsx
app/ui-react/syndesis/src/app/UI.tsx
app/ui-react/syndesis/src/app/UIContext.tsx
app/ui-react/syndesis/src/app/__mocks__/App.tsx
app/ui-react/syndesis/src/app/index.ts
app/ui-react/syndesis/src/index.tsx
app/ui-react/syndesis/src/modules/connections/components/Connections.tsx
app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
app/ui-react/syndesis/src/modules/customizations/pages/ExtensionImportPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
app/ui-react/syndesis/src/shared/WithClosedNavigation.tsx

This fixes a bug with FF going in a render loop sometimes, for example when refreshing a page using the `PageTitle` component.
Also, fixes #206

bugfix: optimize the use of context components to reduce full re-renderings

---

app/ui-react/packages/api/src/WithIntegration.tsx
app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
app/ui-react/syndesis/src/modules/integrations/components/WithIntegrationActions.tsx
app/ui-react/syndesis/src/modules/integrations/components/index.ts
app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx

fixes #196
Did a little re-organizing and added server event driven fetching to `WithIntegration` too.

chore: refactor integration actions into it's own component

---

app/ui-react/packages/api/src/WithIntegrationHelpers.tsx
app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
app/ui-react/packages/ui/src/Integration/Details/IntegrationBulletinBoardAlert.tsx
app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailDescription.tsx
app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailEditableName.tsx
app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
app/ui-react/packages/ui/src/Integration/Details/index.ts
app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
app/ui-react/packages/utils/package.json
app/ui-react/packages/utils/src/dateHelpers.ts
app/ui-react/packages/utils/src/index.ts
app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPageTable.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
app/ui-react/yarn.lock

Brings in moment.js and functions from the angular codebase for formatting some duration values in the UI, takes a todo off the dashboard, tweaks the alignment of a bunch of things and adds in the bulletin board-driven messages and adds the inline edit support for name/description.

feat: finish up detail pages, connect things, align things, show proper duration values

---

app/ui-react/packages/ui/src/Integration/IntegrationEditorChooseAction.tsx
app/ui-react/packages/ui/src/Integration/IntegrationEditorChooseConnection.tsx
app/ui-react/packages/ui/src/Integration/IntegrationEditorForm.tsx
app/ui-react/packages/ui/src/Integration/IntegrationEditorLayout.tsx
app/ui-react/packages/ui/src/Integration/IntegrationEditorNothingToConfigure.tsx
app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
app/ui-react/packages/ui/src/Integration/index.ts
app/ui-react/packages/ui/src/index.css
app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
app/ui-react/syndesis/src/modules/integrations/shared/WithConfigurationForm.tsx

The editor was using a mix of headers around the viewport, this cleans it up.

chore: use pf4 headers for the editor

---

app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx

Instead of showing many alerts of the same type this PR combines them and merges the 'detail' field, so for example this one had tons of the same alert, now it's:
@dongniwang FYI found a nice solution for this nagging problem :-)
For reference, this is what this same integration looked like before:
and in the old app just for funs:

fix: dedupe bulletin board messages and combine details as needed

---

app/ui-react/packages/api/src/helpers/connectionFunctions.ts
app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/api/src/index.ts
app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivity.css
app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivity.tsx
app/ui-react/packages/ui/src/Integration/IntegrationFlowStepDetails.tsx
app/ui-react/packages/ui/src/Integration/IntegrationFlowStepWithOverview.tsx
app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.css
app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.tsx
app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalView.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorSidebar.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts

fix: dump the grid for the horizontal flow view, add links/tooltips to connections

---

app/ui-react/packages/ui/src/Layout/AppLayout.tsx
app/ui-react/packages/ui/src/Shared/AboutModalContent.tsx
app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
app/ui-react/packages/ui/src/Shared/SimplePageHeader.tsx
app/ui-react/packages/ui/src/Support/SupportPageBody.tsx
app/ui-react/packages/ui/src/Support/index.ts
app/ui-react/packages/ui/src/index.ts
app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
app/ui-react/packages/ui/stories/Shared/HelpDropdown.stories.tsx
app/ui-react/packages/ui/tests/AppLayout.spec.tsx
app/ui-react/syndesis/src/app/UI.tsx
app/ui-react/syndesis/src/index.tsx
app/ui-react/syndesis/src/modules/index.ts
app/ui-react/syndesis/src/modules/resolvers.ts
app/ui-react/syndesis/src/modules/routes.ts
app/ui-react/syndesis/src/modules/support/index.tsx
app/ui-react/syndesis/src/modules/support/pages/SupportPage.tsx
app/ui-react/syndesis/src/modules/support/resolvers.ts
app/ui-react/syndesis/src/modules/support/routes.ts

This PR adds items to the help dropdown menu.
Should help resolve https://github.com/syndesisio/syndesis-react/issues/243
TODO: Wire up logout for the user dropdown

feat(help-dropdown): add help dropdown entries

---

app/ui-react/packages/ui/src/Integration/IntegrationEditorStepsList.css
app/ui-react/packages/ui/src/Integration/IntegrationEditorStepsList.tsx
app/ui-react/packages/ui/src/Integration/IntegrationEditorStepsListItem.tsx
app/ui-react/packages/ui/src/Integration/IntegrationFlowAddStep.css
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx

fix: small bugfixes to the IVP and the Add step page

---

app/ui-react/packages/api/src/Fetch.tsx
app/ui-react/packages/api/src/SyndesisFetch.tsx
app/ui-react/packages/api/src/WithActionDescriptor.tsx
app/ui-react/packages/api/src/WithIntegrationHelpers.tsx
app/ui-react/packages/api/src/index.ts
app/ui-react/packages/ui/src/Integration/IntegrationEditorForm.tsx
app/ui-react/packages/ui/src/Integration/IntegrationEditorNothingToConfigure.tsx
app/ui-react/packages/ui/src/Integration/editor/index.ts
app/ui-react/packages/ui/src/Integration/editor/shared/PageSectionLoader.tsx
app/ui-react/packages/ui/src/Integration/editor/shared/index.ts
app/ui-react/packages/ui/src/Integration/index.ts
app/ui-react/packages/utils/src/autoformHelpers.ts
app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
app/ui-react/syndesis/src/modules/integrations/shared/WithConfigurationForm.tsx

feat: fetch the action descriptor up-front

---

app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts

feat: add support for extensions

---

app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.css
app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.tsx
app/ui-react/packages/ui/src/Dashboard/TopIntegrations.css
app/ui-react/packages/ui/src/Integration/IntegrationListItem.css
app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx

- fix alignment of recent integrations
- improvements to top integrations
Mobile:

Recent Integrations & Top Integrations fix

---

app/ui-react/packages/api/src/WithChangeListener.tsx
app/ui-react/packages/api/src/WithConnections.tsx
app/ui-react/packages/utils/src/debounce.ts
app/ui-react/packages/utils/src/index.ts
app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx

fix: cut down on server fetching

---

app/ui-react/packages/ui/package.json
app/ui-react/packages/ui/src/Integration/editor/steps/template/TemplateStepTemplateEditor.tsx
app/ui-react/packages/ui/src/Shared/TextEditor.tsx
app/ui-react/packages/utils/package.json
app/ui-react/packages/utils/src/index.ts
app/ui-react/packages/utils/src/lintHelpers.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/template/WithTemplater.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/abstract-language-lint.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/freemarker-mode-lint.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/index.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/mustache-mode-lint.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/template-symbol.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/velocity-lint.ts
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
app/ui-react/yarn.lock

fixes #268 
relates to #254
Have a look at the "From React" integration on staging to have a play with it.

feat: wire up linting support; 

---

app/ui-react/packages/ui/src/Dashboard/TopIntegrations.css
app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx

To be consistent across both Top Integrations and Recent Updates

Fix label height on Dashboard

---

app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailBreadcrumb.tsx
app/ui-react/packages/ui/src/Integration/editor/steps/template/TemplateStepTemplateEditor.tsx
app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
app/ui-react/packages/ui/src/Shared/WithDropzone.tsx
app/ui-react/packages/ui/src/Shared/index.ts
app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/template/WithTemplater.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPageTable.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx

fixes #274
And I was bored last night so I fixed a couple things that were bugging me.

feat: connect file drag/drop support, misc alignments

---

app/ui-react/packages/ui/src/Integration/IntegrationEditorLayout.tsx

chore: set IDs on save/publish/cancel buttons to ease testing

---

app/ui-react/packages/api/src/WithUser.tsx
app/ui-react/packages/api/src/index.ts
app/ui-react/syndesis/src/app/App.tsx
app/ui-react/syndesis/src/app/AppContext.tsx
app/ui-react/syndesis/src/app/UI.tsx
app/ui-react/syndesis/src/app/__mocks__/App.tsx

feat: fetch the username and use it in the header

---

app/ui-react/packages/api/src/WithExtensionHelpers.tsx
app/ui-react/packages/api/src/callFetch.ts
app/ui-react/syndesis/src/modules/extensions/pages/ExtensionDetailsPage.tsx
app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx
app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx

fixes #279
Also fixes some i18n references in the extension module

fix: Set the right mix of headers for extension upload

---

app/ui-react/packages/api/src/WithServerEvents.tsx
app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx

fixes #288
also adds a fix for #119

feat: wire up publish button and update routing

---

app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx

Fix for integration list label height

---

app/ui-react/packages/ui/src/Integration/IntegrationEditorLayout.css
app/ui-react/packages/ui/src/Integration/IntegrationFlowStep.css
app/ui-react/packages/ui/src/Integration/IntegrationFlowStepDetails.css
app/ui-react/packages/ui/src/Integration/IntegrationVerticalFlow.css
app/ui-react/packages/ui/src/Integration/IntegrationVerticalFlow.tsx

* moves toggle button outside of scrolling IVP
* makes IVP narrower
* repositions icon in IVP toggle button

refactor(IVP): refactors width, scroll, toggle

---

app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivity.css
app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.css
app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx

Integration detail activity
* Change color of last refreshed timestamp and add margin-bottom
* Adjust expanded table styles
Integration detail metrics
* re-order title/body in total errors card
* increase card padding
* normalize card body font styles

fix(integration): fix metrics and activity ui bugs in detail view

---

app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/api/src/useIntegrationHelpers.tsx
app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json

Delete steps in the Edit Integration page.
fix #259

Delete Step in Integration Editor

---

app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/utils.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/DescribeDataShapePage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithDescribeDataShapeForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx

fix: wire up describe data saving and buttons

---

app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListView.css
app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListView.tsx
app/ui-react/packages/ui/src/Integration/IntegrationFlowAddStep.css
app/ui-react/packages/ui/src/Integration/IntegrationFlowAddStep.tsx
app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.css

* adjust text spacing in integration details history list
* remove white background behind from "add step" blue/white plus icon
* remove blue border from step icons in integration details view, increase size

fix(integrationeditor): various ui updates

---

app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx

chore: increase the multi-select widget height

---

app/ui-react/packages/api/src/useIntegrationHelpers.tsx
app/ui-react/packages/ui/src/Integration/IntegrationEditorForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/NothingToConfigure.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx

fix: show error message when submitting an invalid form

---

app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppExpanderBody.tsx

Left aligns the content in the expandable panel on support page.

fix(support): left align expanded panel form

---

app/ui-react/packages/auto-form/src/AutoForm.tsx
app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
app/ui-react/packages/ui/src/Connection/ConnectionDetailsHeader.css
app/ui-react/packages/ui/src/Connection/ConnectionDetailsHeader.tsx

so that it looks closer to this

fix(connection): rework connection details UI

---

app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx

* add underline under create connection wizard card titles
* align connection details card better

fix(connection): update create connection wizard and details cards

---

app/ui-react/packages/ui/src/Connection/ConnectionDetailsHeader.css
app/ui-react/packages/ui/src/Customization/ApiConnectorDetailsForm.css
app/ui-react/packages/ui/src/Customization/ApiConnectorDetailsForm.tsx
app/ui-react/packages/ui/src/Customization/ApiConnectorReview.css
app/ui-react/packages/ui/src/Customization/ApiConnectorReview.tsx
app/ui-react/packages/ui/src/Customization/ExtensionDetail.css
app/ui-react/packages/ui/src/Customization/ExtensionDetail.tsx
app/ui-react/packages/ui/src/Customization/ExtensionIntegrationsTable.tsx
app/ui-react/packages/ui/src/Customization/ExtensionOverview.tsx
app/ui-react/packages/ui/src/Customization/ExtensionSupports.tsx
app/ui-react/packages/ui/src/index.css

General cleanup of the api client connector and extensions detail pages.

Ui react customizations ui cleanup

---

app/ui-react/packages/api/src/WithApiConnectors.tsx
app/ui-react/packages/api/src/WithConnections.tsx
app/ui-react/packages/api/src/WithConnectors.tsx
app/ui-react/packages/api/src/WithExtensions.tsx
app/ui-react/packages/api/src/WithIntegrations.tsx
app/ui-react/packages/api/src/WithOAuthApps.tsx

fix: tell the backend to send us more things

---

app/ui-react/packages/ui/src/Connection/ConnectionCreatorLayout.tsx
app/ui-react/packages/ui/src/Integration/CiCd/CiCdEditDialog.tsx
app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx

* Change "done" button in create connection wizard to "create"
* create space in cicd modal between intro text and form
* align drag 'n drop box with page content

fix(ui): small bugs on connections, cicd, and drag n drop ui

---

app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.css
app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.css
app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.tsx

Now using same styles as other wizards in the ui.  The DV wizards now more consistent and content in scrollable area

TTOOLS-637 DV wizard layouts

---

app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx

- Commented out import/export from virt list page.
- Removed/commented out Relationship and Metrics tabs from virt detail

TTOOLS-636: Commented out functionality not included for the tech preview release.

---

app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx

fix: revert bogus changes, fixes #348

---

app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/api/src/useIntegrationHelpers.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
app/ui-react/syndesis/src/shared/WithLeaveConfirmation.tsx

Fixes https://github.com/syndesisio/syndesis/issues/5507
Fixes #350

fix: proper saving and publishing of an integration

---

app/ui-react/packages/auto-form/src/AutoForm.tsx

fix: optional initialValue prop for auto-form

---

app/ui-react/packages/api/src/WithSteps.tsx
app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/utils.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts

fixes syndesisio/syndesis#5498
fixes syndesisio/syndesis#4207

fix: bring the data mapper step back from vacation

---

app/ui-react/packages/ui/src/Connection/ConnectionCreatorLayout.tsx
app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
app/ui-react/packages/ui/src/Layout/WizardSteps.tsx
app/ui-react/packages/ui/src/index.css
app/ui-react/syndesis/src/modules/connections/ConnectionsCreatorApp.tsx
app/ui-react/syndesis/src/modules/connections/components/ConnectionCreatorBreadSteps.tsx
app/ui-react/syndesis/src/modules/connections/components/ConnectionCreatorBreadcrumb.tsx
app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
app/ui-react/syndesis/src/modules/connections/components/index.ts
app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
app/ui-react/syndesis/src/modules/connections/pages/create/index.ts
app/ui-react/syndesis/src/modules/connections/pages/index.ts

Fixes https://github.com/syndesisio/syndesis/issues/5470
Also, some UI finetuning.

fix: connection creation bugfixes

---

app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.css
app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx
app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.css
app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json

Trello card: https://trello.com/c/q73yIflP/8-m-api-provider-editor

API Editor UI Round II

---

app/ui-react/packages/auto-form/src/AutoForm.tsx
app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
app/ui-react/packages/auto-form/stories/Array.stories.tsx
app/ui-react/packages/auto-form/stories/KitchenSink.stories.tsx
app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx

fixes #377
fixes syndesisio/syndesis#5530

fix: rework how initial validation is performed

---

app/ui-react/packages/ui/src/Layout/ButtonLink.tsx

Fixes https://github.com/syndesisio/syndesis/issues/5527#event-2380415787

fix: make sure that onClick event handlers are fired only once

---

app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/EditSpecificationPage.tsx
app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json

Fixes https://github.com/syndesisio/syndesis/issues/5548

fix: some i18n error

---

app/ui-react/packages/auto-form/src/utils.ts
app/ui-react/packages/utils/src/autoformHelpers.ts

Fixes https://github.com/syndesisio/syndesis/issues/5566
Fixes https://github.com/syndesisio/syndesis/issues/5572
Fixes https://github.com/syndesisio/syndesis/issues/5559

fix: hide hidden fields and consider them not required for validation purposes

---

app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx

Fixes https://github.com/syndesisio/syndesis/issues/5583

fix: broken step configuration

---

app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/api/src/useIntegrationHelpers.tsx

Fixes https://github.com/syndesisio/syndesis/issues/5565

fix: sanitize the integration object before saving

---

app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.css
app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx

fixes https://github.com/syndesisio/syndesis-react/issues/395
* apply white-space: nowrap to integration details activity status column
* fix spacing in api client connector drag 'n drop upload
Integration details - activity output
* fix text not wrapping
* show 'no output' for empty output
* rework background color

fix(ui): integration details, api connector upload

---

app/ui-react/packages/ui/src/Layout/AppLayout.tsx
app/ui-react/packages/ui/src/Layout/AppTopMenu.tsx
app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
app/ui-react/packages/ui/tests/AppLayout.spec.tsx

This PR applies more general cleanup and fine tuning of the UI.
remove unnecessary toolbar group
use kebab toggle
add test ids
replace missing test for header menus
automatically close the sidebar menu on small screen sizes
add skip to content link for accessibility

chore(ux): apply followup ux feedback

---

app/ui-react/packages/api/src/helpers/integrationFunctions.ts

Fixes https://github.com/syndesisio/syndesis-react/issues/415

fix: properly handle the integration id for new integrations

---

app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.css
app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.css
app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.tsx

- reduce height of ConnectionSchemaListItem and ViewInfoListItem used in the DV wizards
- change relative sizing of SqlResults in SqlClientContent to allow more room for results display.

TTOOLS-624 improvements to DV wizard lists

---

app/ui-react/packages/ui/src/Layout/AppTopMenu.tsx
app/ui-react/packages/ui/src/Shared/AboutModalContent.tsx
app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
app/ui-react/packages/ui/stories/Shared/AboutModal.stories.tsx
app/ui-react/syndesis/src/app/UI.tsx
app/ui-react/syndesis/src/app/locales/app-translations.en.json
app/ui-react/syndesis/src/app/locales/app-translations.it.json

- see syndesisio/syndesis#5584
- see syndesisio/syndesis#5585
- added test ID to top menu user dropdown
- added test IDs to the about dialog
- i18n'd `AboutModalContent`

Test identifier work

---

app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.tsx
app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportCard.tsx
app/ui-react/packages/ui/src/Customization/extensions/ExtensionListItem.tsx
app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.css
app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx
app/ui-react/packages/ui/src/Integration/Import/ImportPageUI.tsx
app/ui-react/packages/ui/stories/Customization/ExtensionImportCard.stories.tsx
app/ui-react/packages/ui/tests/Customization/ExtensionImportCard.spec.tsx
app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx

* add page title layout to import extension page
* wrap extension import dnd box in card
* fix extension list view details/update/delete button alignment/spacing
* fix api client connector list view details/delete button alignment
* add space between "view" and kebab dropdown in integration list items

fix(ui): various UI improvements

---

app/ui-react/packages/models/src/dv.d.ts
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts

- ENTESB-10794 Adds odata link to the virtualization list item, when available
- TTOOLS-628 Adds virtualization publish log link, when available

Adds odata link to the virtualization list item

---

app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorActionsListItem.tsx

Fix for Integration Editor Action ListItem row

---

app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContent.stories.tsx
app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx

Fixes for ENTESB-10792
- add title and row count above results table - SqlClientContext
- WithVirtualizationSqlClientForm - fixes row and column handling when there are no rows returned.
- VirtualizationUtils now escapes preview query names in the event that the connection has a special character
- fix issue from previous commit - additionalInfo in VirtualiationListItem was not specified correctly

Fixes for query client issues

---

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx

fixes https://github.com/syndesisio/syndesis/issues/5615

Auto-validate for apiKey type

---

app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json

fix: Add syntax examples in condition help block

---

app/ui-react/packages/ui/src/Dashboard/Dashboard.css
app/ui-react/packages/ui/src/Dashboard/TopIntegrations.css
app/ui-react/packages/ui/src/Dashboard/TopIntegrationsCard.tsx
app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.css
app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
app/ui-react/packages/ui/src/Shared/ProgressWithLink.css
app/ui-react/packages/ui/src/index.css

Fixes https://github.com/syndesisio/syndesis-react/issues/399

fix(integrationlist): fix list row item overlap

---

app/ui-react/packages/api/src/constants.ts
app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/ui/src/Integration/ConditionsDropdown.tsx
app/ui-react/packages/ui/src/Integration/ConditionsDropdownBody.tsx
app/ui-react/packages/ui/src/Integration/index.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx

fixes syndesisio/syndesis#5515
fixes syndesisio/syndesis#5636
fixes syndesisio/syndesis#5608
improves navigation

various conditional flow fixes

---

app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts

fixes syndesisio/syndesis#5626

fix: hook up the describe data link

---

app/ui-react/packages/api/src/WithUserHelpers.tsx
app/ui-react/syndesis/public/logout.html
app/ui-react/syndesis/src/app/UI.tsx
app/ui-react/syndesis/src/setupProxy.js

Fixes https://github.com/syndesisio/syndesis/issues/5573

fix: logout

---

app/ui-react/packages/ui/src/Connection/ConnectionCard.css
app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.css
app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx
app/ui-react/packages/ui/src/Shared/DndFileChooser.css
app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.css
app/ui-react/packages/ui/src/index.css

fixes https://github.com/syndesisio/syndesis/issues/5627
Connection card
* make sure icon/headings are aligned
* absolutely position tech preview
* disable title hover styles
----
* Fix misalignment of API provider operation list
* remove drag 'n drop left indent
* Space out lines in drag and drop box
* Set global pf4 font size to sm (12px), and remove 'font-size' declaration from body
* keep list view title/name cell from breaking in middle of word

fix(ui): various fixes

---

app/ui-react/packages/api/src/WithSteps.tsx
app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/auto-form/package.json
app/ui-react/packages/auto-form/src/utils.ts
app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
app/ui-react/packages/auto-form/src/widgets/TextButton.tsx
app/ui-react/syndesis/src/app/App.css
app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx

fixes syndesisio/syndesis#5671
fixes syndesisio/syndesis#5676
fixes syndesisio/syndesis#5636
fixes syndesisio/syndesis#5691
fixes syndesisio/syndesis#5652

auto form and conditional flow bug fixes

---

app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx

When `GET /api/v1/connectors/{id}/credentials` returns `{}` we should not invoke a `POST /api/v1/connectors/{id}/credentials`.
This makes it so that the invocation of `useOAuthFlow` is conditional on the result of `useConnectorCredentials`.

refactor(oauth): prevent credentials POST for non-OAuth

---

app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.tsx
app/ui-react/packages/ui/src/Shared/TextEditor/TextEditor.css
app/ui-react/packages/ui/src/Shared/TextEditor/TextEditor.tsx

Rebased previous PR
- enable sql keyword highlighting in view editor
- code completion will require more work to supply the hintOptions

TT-598 View editor highlighting

---

app/ui-react/syndesis/src/app/App.tsx
app/ui-react/syndesis/src/app/index.ts
app/ui-react/syndesis/src/index.tsx

Also, unregister previously registered workers for good measure.
Related issue https://github.com/syndesisio/syndesis/issues/5602

chore: disable the service worker

---

app/ui-react/packages/ui/src/Layout/AppLayout.tsx
app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
app/ui-react/packages/ui/tests/AppLayout.spec.tsx
app/ui-react/syndesis/src/app/UI.tsx

Relative issue https://github.com/syndesisio/syndesis/issues/5619

fix: make the logo link use the html5 history push

---

app/ui-react/packages/atlasmap-assembly/src/app/app.component.css
app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx

Relative issue https://github.com/syndesisio/syndesis/issues/5699

fix: allow atlasmap viewport to scroll if needed

---

app/ui-react/packages/auto-form/src/utils.ts
app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx

fixes syndesisio/syndesis#5676

fix: moar careful initial value massaging for array entries

---

app/ui-react/syndesis/config.minishift.json
app/ui-react/syndesis/config.proxy.json
app/ui-react/syndesis/config.staging.json
app/ui-react/syndesis/src/app/WithConfig.tsx
app/ui-react/syndesis/src/app/__mocks__/WithConfig.tsx
app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx

Depends on https://github.com/syndesisio/syndesis/pull/5726
https://github.com/syndesisio/syndesis/issues/5475

Fixes #5475 Disable DataVirt UI when Komodo server isn't present

---

app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx

for syndesisio/syndesis#5215
also relates to https://github.com/syndesisio/syndesis/issues/5716

fix: apply the data shape of the conditional flow's step adapted data shape to each conditional flow

---

app/ui-react/syndesis/config.minishift.json
app/ui-react/syndesis/config.proxy.json
app/ui-react/syndesis/config.staging.json

@riccardo-forina @mdrillin FYI

re-enable datavirt for development by default
