package.json
packages/models/package.json
syndesis/package.json
yarn.lock

`event-stream` was used by npm-run-all. This upgrades it to the latest version, that uses safe dependencies.
```
$ npm ls event-stream
@syndesis/monorepo@0.1.0 /Users/riccardoforina/Code/syndesis-react
└─┬ npm-run-all@4.1.3
└─┬ ps-tree@1.1.0
└── event-stream@3.3.6
```
Fixes #30

chore: upgrade npm-run-all to v4.1.5 to fix a security issue with event-stream

---

packages/api/src/WithIntegrations.tsx
packages/api/src/WithMonitoredIntegrations.tsx
packages/models/src/extra.d.ts
packages/ui/src/IntegrationProgress.css
packages/ui/src/IntegrationProgress.tsx
packages/ui/src/IntegrationStatus.tsx
packages/ui/src/IntegrationStatusDetail.tsx
packages/ui/src/IntegrationsListItem.tsx
packages/ui/src/index.ts
packages/ui/src/sharedModels.ts
packages/ui/stories/IntegrationProgress.stories.tsx
packages/ui/stories/IntegrationStatusDetail.stories.tsx
packages/ui/tests/ConnectionCard.spec.tsx
packages/ui/tests/IntegrationProgress.spec.tsx
packages/ui/tests/IntegrationStatusDetail.spec.tsx
syndesis/src/app/App.tsx
syndesis/src/app/AppContext.tsx
syndesis/src/i18n/locales/shared-translations.en.json
syndesis/src/i18n/locales/shared-translations.it.json
syndesis/src/modules/dashboard/pages/DashboardPage.tsx
syndesis/src/modules/integrations/locales/integrations-translations.en.json
syndesis/src/modules/integrations/locales/integrations-translations.it.json
syndesis/src/modules/integrations/pages/IntegrationsPage.tsx

fixes #37 - adds storybooks and tests for IntegrationProgress and IntegrationStatusDetail, and adds the log link property to both.
Also tweaks how the detailed status is fetched from the server it'll be driven by integration deployment changes vs polling.
TODO
* feedback?
* ~~rebase to pick up i18n changes~~
* ~~More manual testing with the backend to see how the detailed status works in the integration list~~
* ~~Calculate the log link somewhere and pass it in so it works~~

feat: finish up the detailed integration status

---

packages/auto-form/.storybook/StoryHelper.css
packages/auto-form/.storybook/StoryHelper.tsx
packages/auto-form/.storybook/addons.js
packages/auto-form/.storybook/config.js
packages/auto-form/.storybook/webpack.config.js
packages/auto-form/package.json
packages/auto-form/src/AutoForm.tsx
packages/auto-form/src/FormBuilder.tsx
packages/auto-form/src/index.ts
packages/auto-form/src/models.ts
packages/auto-form/src/widgets/FormCheckboxComponent.tsx
packages/auto-form/src/widgets/FormHiddenComponent.tsx
packages/auto-form/src/widgets/FormInputComponent.tsx
packages/auto-form/src/widgets/FormSelectComponent.tsx
packages/auto-form/src/widgets/FormTextAreaComponent.tsx
packages/auto-form/src/widgets/index.ts
packages/auto-form/stories/AutoForm.stories.tsx
packages/auto-form/tests/AutoForm.spec.tsx
packages/auto-form/tsconfig.json
packages/auto-form/tsconfig.storybook.json
packages/auto-form/tslint.json
packages/models/src/extra.d.ts
syndesis/package.json
yarn.lock

First spike for #3 
Figured I'd take a poke at using Formik, so with some copypasta to create a new package I threw together @riccardo-forina's suggestions and it didn't destroy the multiverse :-)  The usage is pretty simple:
```
<AutoForm
definition={formDefinition}
initialValues={initialValue}
onSave={onSave}
/>
```
Where `definition` is the map of `ConfigurationProperty` and `initialValues` would be the usual `configuredProperties` from the backend.
I didn't wind up using the patternfly-react form components to start off with as I wanted to be sure the binding all worked as expected.
Using the AMQ configuration properties and some made-up ones:
Clicking submit after mucking with some values:
TODO - some of these it might be better to iterate on
* feedback?
* ~~Support more types …

feat: add an auto-form package to generate forms using Formik; fixes #3

---

packages/auto-form/.storybook/config.js
packages/auto-form/package.json
packages/auto-form/src/FormBuilder.tsx
packages/auto-form/src/widgets/FormCheckboxComponent.tsx
packages/auto-form/tests/AutoForm.spec.tsx
yarn.lock

This PR teaches auto-form to use the PF3 checkbox.
Step toward resolving https://github.com/syndesisio/syndesis-react-poc/issues/46
add patternfly-react as an auto-form dependency
turn off a11y checks until storybook stops throwing errors
account for checkboxes when massaging values (massageValue in FormBuilder)
use components from patternfly-react to build out the FormCheckboxComponent
improve tests for text input, add new tests for checkbox

feat(checkbox): add support for basic pf3 checkbox

---

packages/auto-form/package.json
packages/auto-form/src/widgets/FormCheckboxComponent.tsx
packages/auto-form/stories/FormCheckboxComponent.stories.tsx
yarn.lock

This PR adds support for disabled and validationState states in checkbox. It also adds a storybook entry that exercises the checkbox properties. 
add support for disabled state in checkbox
add storybook react types
add storybook entry for checkbox

feat(checkbox): add support for disabled state and storybook

---

packages/auto-form/src/models.ts
packages/auto-form/src/widgets/FormCheckboxComponent.tsx
packages/auto-form/src/widgets/FormTextAreaComponent.tsx
packages/auto-form/stories/FormCheckboxComponent.stories.tsx
packages/auto-form/stories/FormTextAreaComponent.stories.tsx
packages/auto-form/tests/FormCheckboxComponent.spec.tsx
packages/auto-form/tests/FormTextAreaComponent.spec.tsx

This PR introduces dedicated test suites for checkbox and textarea, and also provides some basic interfaces to make using these components a little easier.
Steps toward resolving https://github.com/syndesisio/syndesis-react-poc/issues/46
add new models to represent form fields
add test suite for textarea and checkbox form component

chore(form-controls): more test coverage and types for formcontrols

---

packages/auto-form/src/models.ts
packages/auto-form/src/widgets/FormInputComponent.tsx
packages/auto-form/stories/FormCheckboxComponent.stories.tsx
packages/auto-form/stories/FormInputComponent.stories.tsx
packages/auto-form/stories/FormTextAreaComponent.stories.tsx
packages/auto-form/tests/FormInputComponent.spec.tsx

This PR converts our text input to use components provided by patternfly3. It also adds a corresponding storybook entry as well as basic unit tests.
Steps toward solving https://github.com/syndesisio/syndesis-react-poc/issues/46
add pf3 text input
storybooks for text, pwd, and num
add tests
clean up other form control tests

feat(textinput): add support for pf3 text input control

---

packages/auto-form/src/widgets/FormCheckboxComponent.tsx
packages/auto-form/src/widgets/FormSelectComponent.tsx
packages/auto-form/stories/FormSelectComponent.stories.tsx
packages/auto-form/tests/FormSelectComponent.spec.tsx

This PR adds the pf3 FormControl as the building block for our select component. Also adds a dedicated storybook entry and corresponding test suite.
I also removed the onChange binding in checkbox component, because it works with or without this. Can add it back if/when we determine it's actually doing something necessary. Will probably become relevant as we begin to add more features to our form components, like validation.
Step toward resolving https://github.com/syndesisio/syndesis-react-poc/issues/46
add tests
add stories
remove unnecessary onChange binding from checkbox

feat(select): use pf3 FormControl for select component

---

packages/ui/src/Integration/IntegrationDetailHistoryListView.tsx
packages/ui/src/Integration/IntegrationDetailHistoryListViewItem.tsx
packages/ui/src/Integration/index.ts
packages/ui/stories/Integration/IntegrationDetailHistoryListView.stories.tsx
packages/ui/stories/Integration/IntegrationDetailHistoryListViewItem.stories.tsx

Opening this as a WIP/Draft Pull Request as I have some questions before I make this ready for review. Will also try to add the other sections of the Details tab if possible.
Changes:
- Add IntegrationDetailHistoryListView component and story.
- The history section, slightly confusingly, includes a row for Draft options, and then a series of rows for History items, see [this](https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/integrations/i-LYmlhVFB6pKKaBQVSyez) example in staging. So, I have moved the Draft row of options to this here List View component and story (from the List View Item), as it made it easier to work with the data.
Questions:
- ~Is it possible to extract data for stories that would like to reference the same data item? For example, some integration properties …

feature(integrationDetailHistoryListView)

---

packages/api/src/WithExtensionHelpers.tsx
packages/api/src/callFetch.ts
packages/api/src/index.ts
packages/ui/src/Customization/ExtensionDetail.tsx
packages/ui/src/Customization/ExtensionListItem.tsx
packages/ui/src/Shared/DeleteConfirmationDialog.tsx
packages/ui/src/Shared/index.ts
packages/ui/stories/Customization/ExtensionDetail.stories.tsx
packages/ui/stories/Customization/ExtensionListItem.stories.tsx
packages/ui/stories/Customization/ExtensionListView.stories.tsx
packages/ui/stories/Shared/DeleteConfirmationDialog.stories.tsx
syndesis/src/modules/customizations/locales/customizations-translations.en.json
syndesis/src/modules/customizations/locales/customizations-translations.it.json
syndesis/src/modules/customizations/pages/ExtensionDetailsPage.tsx
syndesis/src/modules/customizations/pages/ExtensionsPage.tsx

- work supporting issue #78
- created DeleteConfirmationDialog as a shared component
- created DeleteConfirmationDialog story
- added delete extension functionality to ExtensionsPage
- added delete extension functionality to ExtensionDetailsPage (displays list view after delete)
- created WithExtensionHelpers to centrally manage deleted functionality
- updated affected existing stories

Implements Extension Delete Functionality

---

packages/api/src/WithVirtualizationHelpers.tsx
packages/ui/src/Data/Virtualizations/VirtListView.tsx
packages/ui/stories/Data/Virtualizations/VirtListView.stories.tsx
syndesis/src/i18n/locales/shared-translations.en.json
syndesis/src/i18n/locales/shared-translations.it.json
syndesis/src/modules/data/locales/data-translations.en.json
syndesis/src/modules/data/locales/data-translations.it.json
syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
syndesis/src/modules/data/pages/VirtualizationsPage.tsx
syndesis/src/modules/resolvers.ts

- add createVirtualization function to WithVirtualizationHelpers
- username prop was added to WithVirtualizationHelpers.  many of the repo paths require the username as part of the path.  
- modified the VirtualizationCreatePage to contain the form for entering a name and description.  Upon successful create, user is routed to list page.  (in future, this will route to details page instead)
- additions to i18n, plus other minor changes.

TTOOLS-588 Adds CreateVirtualization

---

README.md
packages/auto-form/yalc.lock

This PR cleans up the README. Updating old links, adding some additional info around the getting started steps, and improving the syntax highlighting for code examples.
Sorry about the extra noise for trimming trailing whitespace.

fix(readme): correct broken links, improve getting started steps

---

packages/ui/stories/Customization/ExtensionDetail.stories.tsx
packages/ui/stories/Customization/ExtensionImport.stories.tsx
packages/ui/stories/Customization/ExtensionListItem.stories.tsx
packages/ui/stories/Customization/ExtensionListView.stories.tsx
packages/ui/stories/Customization/ExtensionsPage.stories.tsx
syndesis/src/modules/customizations/pages/ExtensionsPage.tsx

This PR thanks to @riccardo-forina and live code share earlier today.
Changes:
- Write stories for Extension Page.
- Group Extension Page stories together in Storybook.
- Remove `this.state` reference no longer in use.
Some screenshots:

Add Customizations Extensions Page stories

---

packages/ui/src/Data/Views/ViewList.tsx
packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
packages/ui/stories/Data/Views/ViewList.stories.tsx
packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
syndesis/src/modules/data/pages/VirtualizationsPage.tsx

Fixes issue where EmptyState was not being displayed for the virtualization and view list.  The page is now responsible for setting when the list has data.

Fix for Virtualization list EmptyState

---

packages/ui/src/Integration/IntegrationsListItemUnreadable.tsx
packages/ui/src/Integration/index.ts
syndesis/src/modules/integrations/components/Integrations.tsx
syndesis/src/shared/PageTitle.tsx
syndesis/src/shared/WithErrorBoundary.tsx

This adds a way to catch errors when rendering integration items, and shows a fallback instead. 
It is in no way to be considered the best way to deal with this kind of problem, it's just a patch; that said, I think the approach is interesting and we could try it out and in case, extend it/make it better.
Some bogus integrations.
What is displayed clicking on the "Integration JSON" button.

feat: adds some error resilience to the UI

---

syndesis/src/shared/WithClosedNavigation.tsx

Drop the class in favor of hooks to work around the deprecated usage of `this.context` in the class.
Fixes #104

bugfix: drop the class in favor of hooks

---

.circleci/config.yml
app/ui-react/README.md

This should make the built UI - the one under GH pages - accessible again

chore: fix some broken links

---

app/ui-react/packages/ui/src/Customization/ExtensionDetail.tsx
app/ui-react/packages/ui/src/Customization/ExtensionListItem.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
app/ui-react/packages/ui/src/Shared/ConfirmationDialog.tsx
app/ui-react/packages/ui/stories/Shared/ConfirmationDialog.stories.tsx
app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json

fixes #149
Adds dialog prompts for starting, stopping and deleting an integration.  Refactors the DeleteConfirmationDialog widget to ConfirmationDialog, and exposes properties to control the button text, class, and icon, for the latter two I opted for enums that map to the underlying patternfly class that the component is expecting.
@mdrillin Hope you don't mind!  I adapted your most recent changes so worth taking a scan and make sure that's okay.

feat: add dialog prompts for life-changing things; refactor delete confirmation dialog

---

app/ui-react/packages/api/src/WithViewEditorStates.tsx
app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
app/ui-react/syndesis/src/modules/data/shared/ViewSqlForm.tsx
app/ui-react/syndesis/src/modules/data/shared/ViewSqlFormAndTable.tsx
app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts

Made some adjustments for the SqlClientPage and components to utilize a preview vdb.
- VirtualizationSqlClientPage now uses the ViewEditorStates instead of getting just the view names.  The ViewEditorState has more info needed for generating preview SQL, etc.
- WithViewEditorStates now allows specification of idPattern, so subset of states can be obtained.
- Now returning actual query results from WithVirtualizationHelpers function.
- changed ViewSqlForm props to specify targetVdb and viewDefinition.  The ViewSqlForm also now defers to VirtualizationUtils function to generate the preview sql.
There are several todos remaining, but I think @blafond has logged them under separate issues.

TTOOLS-601 Improvements to VirtualizationSqlClientPage

---

app/ui-react/packages/models/src/dv.d.ts
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatus.css
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatus.tsx
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatusDetail.css
app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatusDetail.tsx
app/ui-react/packages/ui/src/Integration/IntegrationProgress.css
app/ui-react/packages/ui/src/Integration/IntegrationStatusDetail.tsx
app/ui-react/packages/ui/src/Integration/index.ts
app/ui-react/packages/ui/src/Shared/ProgressWithLink.css
app/ui-react/packages/ui/src/Shared/ProgressWithLink.tsx
app/ui-react/packages/ui/src/Shared/index.ts
app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationPublishStatusDetail.stories.tsx
app/ui-react/packages/ui/stories/Shared/ProgressWithLink.stories.tsx
app/ui-react/packages/ui/tests/ProgressWithLink.spec.tsx
app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts

Adds progress bar for status updates when virtualization is being published, similar to integrations progress bar.
- renames IntegrationProgress to ProgressWithLink and moves it into /Shared.  Update usages, stories and tests accordingly.
- VirtualizationPublishStatusDetail component is updated to use the shared component
- Add VirtualizationPublishingDetails model, and add function in VirtualizationUtils to return the publishing details for a virtualization
- updates data stories

Add progress bar for virtualization publishing status

---

app/ui-react/packages/api/src/WithViewEditorStates.tsx
app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx
app/ui-react/packages/api/src/WithVirtualizations.tsx
app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx

- updates WithViewEditorStates and WithVirtualizations to extend IFetchState, same as @gashcrumb did with environments.  Thanks @gashcrumb !
- VirtualizationsPage and VirtualizationViewPage then call the read operation to trigger the list update.  (the nesting of the With components was changed too)
- Separate change was made in VirtualizationCreatePage, to route to details page upon create - instead of back to the summary page.

TTOOLS-615 Updates Virtualization and View lists upon delete

---

app/ui-react/packages/api/src/WithIntegrationHelpers.tsx
app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/api/tests/helpers/integrationFunctions.spec.tsx
app/ui-react/packages/models/src/models-internal.d.ts
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
app/ui-react/syndesis/src/modules/integrations/resolvers.ts
app/ui-react/syndesis/src/modules/integrations/routes.ts

Ported the logic from the Angular codebase, steps should now be filtered based on the current integration object and the position.
Also switched to flow ids instead of the positional index, to align to how the functions work.

feat: show steps based on the integration and position; switch to flow id instead of idx

---

app/ui-react/packages/ui/src/Shared/ListViewToolbar.tsx
app/ui-react/packages/ui/tests/Customization/ExtensionListView.spec.tsx

fix: hide the results bar when there's no filters active

---

app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/ui/src/Integration/IntegrationEditorChooseAction.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/api-provider/EditPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/api-provider/ReviewPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/api-provider/UploadPage.tsx
app/ui-react/syndesis/src/modules/integrations/index.tsx
app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
app/ui-react/syndesis/src/modules/integrations/resolvers.ts
app/ui-react/syndesis/src/modules/integrations/routes.ts

This introduces the `EditorApp` component, a pluggable "app" that will handle the routes required to handle adding/editing a step to an integration.
Its main goal is to make sure that regardless of where the app has been plugged, all the required routes and sub-components will be set. This together with the previous PR #163 should remove the risk of extending the editor with new features forgetting to do it everywhere is needed.
There are a lot of `TODO` placeholders for the pages right now, but the basic routing and wiring should be in place. Clicking on any step object when adding a step to an integration should never give an error, but redirect to the right URL and show a "TODO" as the page content.
I'm not super happy about how the whole thing looks right now, there is _a lot_ of code …

chore: editor placeholder pages

---

app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/api/tests/helpers/integrationFunctions.spec.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
app/ui-react/syndesis/src/modules/integrations/resolvers.ts

The href selection logic is now shared between the SelectConnection and AddStep components.
Clicking on anything but an endpoint will still crash the app btw.

bugfix: don't crash editing an integration with steps other than endpoints

---

app/ui-react/packages/api/src/WithIntegrationMetrics.tsx
app/ui-react/packages/api/src/index.ts
app/ui-react/packages/ui/src/Integration/IntegrationDetailMetrics.tsx
app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
app/ui-react/syndesis/src/modules/integrations/resolvers.ts
app/ui-react/syndesis/src/modules/integrations/shared/IntegrationDetailNavBar.tsx

- incorporates refactoring changes from @gashcrumb 's PR here https://github.com/syndesisio/syndesis-react/pull/220
- adds functionality to metrics tab, using UI component
- updated to correct interface, where date is a string, unlike what the API returns. we need to add `parseInt()` instead of `newDate` but i'm out of time.

Integration Detail: Metrics tab

---

.circleci/config.yml
app/ui-react/.dockerignore
app/ui-react/Dockerfile
app/ui-react/nginx-syndesis.conf
app/ui-react/nginx.repo
install/generator/02-syndesis-image-streams.yml.mustache
install/syndesis.yml

Bit more info in the commit messages.
This adds a `Dockerfile` ported over from the origin fork and sets the `syndesis.yml` template to use the tag `latest-react` (this enables the use of minishift via `syndesis minishift --install --local`). Also adds CircleCI configuration to build and publish to Docker Hub.

Docker image build and push from CI

---

.circleci/config.yml

Since `persist_to_workspace` is configured with `~/repo/app/ui-react` as
`root` we do not need the `working_directory`.

fix: CircleCI `publish` operates in `~`

---

.circleci/config.yml

Seems like the default for CircleCI is to look into
`/home/circleci/project` so this restores the persisted files to that
location in order for the Docker Orb to work.
File under you-live-you-learn.

fix: CircleCI `publish` operates in `~/project`

---

.circleci/config.yml

Seems that the CircleCI Orb commands are independently configured so we
need to repeat the image/tag parameters.

fix: fix: CircleCI `publish` image/tag for push

---

.circleci/config.yml

Wrong indent of the `image` parameter in YAML build configuration caused
it not to be used.

fix: `deploy` command `image` parameter ident

---

.circleci/config.yml

For aesthetics (bit less YAML) and maintenance (use more defaults), this uses the Docker publish orb's job instead of commands in a custom job.
Also found an orb that seems more _official_ and supports a tag on push.

refactor: ci docker build publish

---

.circleci/config.yml

Turns out that I should read the source of the Docker Orb a bit better,
it is not sufficient to just specify the `path`, `dockerfile` needs to
be specified also.

fix: ci docker publish, specify Dockerfile path

---

app/ui-react/packages/ui/src/Layout/ButtonLink.tsx
app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
app/ui-react/packages/ui/src/Shared/Notifications.tsx
app/ui-react/syndesis/package.json
app/ui-react/syndesis/public/manifest.json
app/ui-react/syndesis/src/app/UI.tsx
app/ui-react/typings/workbox-window/index.d.ts
app/ui-react/typings/workbox-window/package.json

When building the app for production, a service worker is automatically installed and executed every time the app is loaded by the browser. If a new version of the application is available, the assets (js, css, images) are downloaded in background while the user is working, and a persistent toast is eventually displayed to inform the user of the fact, providing a link to click to update the application.
If the user decides to dismiss the toast or reloads the page without clicking the link in the toast, the old version of the app will be loaded instead, and the toast is displayed again. This will continue until the user clicks the link in the toast.
For this to work on the [new staging environment](https://syndesis-react-staging.b6ff.rh-idev.openshiftapps.com), if you have already visited …

feat: show a notification when a new version of the app is available

---

app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/ui/package.json
app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
app/ui-react/packages/ui/src/Integration/editor/index.ts
app/ui-react/packages/ui/src/Integration/editor/steps/index.ts
app/ui-react/packages/ui/src/Integration/editor/steps/template/TemplateStepCard.tsx
app/ui-react/packages/ui/src/Integration/editor/steps/template/TemplateStepTemplateEditor.tsx
app/ui-react/packages/ui/src/Integration/editor/steps/template/TemplateStepTypeSelector.tsx
app/ui-react/packages/ui/src/Integration/editor/steps/template/index.ts
app/ui-react/packages/ui/src/Shared/TextEditor.tsx
app/ui-react/packages/ui/src/Shared/index.ts
app/ui-react/packages/ui/stories/Integration/editor/steps/TemplateStep.stories.tsx
app/ui-react/packages/ui/stories/Shared/TextEditor.stories.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/template/WithTemplater.tsx
app/ui-react/syndesis/src/modules/integrations/resolvers.ts
app/ui-react/yarn.lock

relates to #254
It loads/saves the `configuredProperties` to the step, still need to implement the linting support/validation and file drag/drop functionality.

feat: wire in the template step page and get it saving/loading

---

app/ui-react/packages/ui/src/Connection/ConnectionCard.css
app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx

- Fix kebab misalignment
- Add dropshadow to card on hover, remove underline and hyperlink color
- Improve aesthetics of card, add padding and increase height
- Change check for `techPreview` and rename `tech-preview` class in footer to `config-required`, which makes more sense.
Hover:
fix #249

Connection Card match previous styles, fix kebab

---

app/ui-react/packages/api/src/Fetch.tsx
app/ui-react/packages/api/src/WithApiConnectors.tsx
app/ui-react/packages/api/src/WithChangeListener.tsx
app/ui-react/packages/api/src/WithConnections.tsx
app/ui-react/packages/api/src/WithConnectors.tsx
app/ui-react/packages/api/src/WithExtensionIntegrations.tsx
app/ui-react/packages/api/src/WithExtensions.tsx
app/ui-react/packages/api/src/WithIntegration.tsx
app/ui-react/packages/api/src/WithIntegrations.tsx
app/ui-react/packages/api/src/WithMonitoredIntegration.tsx
app/ui-react/packages/api/src/WithMonitoredIntegrations.tsx
app/ui-react/packages/api/src/WithServerEvents.tsx

fixes #119 
I was totally gonna sneak this onto my last PR but @riccardo-forina merged it while I had stepped away :-)
Anyway, this fully fixes #119, I noticed that the app wasn't reverting back to showing the items once successfully reconnecting.  This ensures that when we reconnect and receive a connected event from the server the app will re-read, and that read will clear any previous read errors.  So if you don't happen to refresh the page it'll just go back to showing whatever list you were looking at.

feat: re-fetch upon receiving connected message; clear error on read

---

app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx
app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
app/ui-react/packages/ui/src/index.css
app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx

This PR updates the integration list page with some UX and styling improvements. 
move config required notice to its own column
align font sizes in integration list rows
view integration button is now secondary
include integration description in the integration list

chore(integration-list-view): clean up styles around integration list

---

app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts

Fix the API provider detection logic.
Fix the URL composition for Atlasmap, checking if we are dealing with absolute or relative paths and act accordingly.
CC @igarashitm one thing that's not clear to me if the `baseMappingServiceUrl` property in the configuration plays a role or not with the other URLs - `baseJavaInspectionServiceUrl`, `baseXMLInspectionServiceUrl`, `baseJSONInspectionServiceUrl`. Right now the logic is that if `baseMappingServiceUrl` is not contained in the specialized URL, we prepend it to it. Logic [is here](https://github.com/syndesisio/syndesis-react/compare/master...riccardo-forina:bugfixes?expand=1#diff-b9d98e0dd7b4c930d63d5c031dff8d6aR84)
Does it sound correct to you?

fix: api provider detection and atlasmap url composition

---

app/ui-react/packages/auto-form/src/AutoForm.tsx
app/ui-react/packages/ui/src/Integration/IntegrationEditorForm.tsx
app/ui-react/packages/ui/src/Integration/editor/endpoint/DescribeDataShapeForm.tsx
app/ui-react/packages/ui/src/Shared/TextEditor.tsx
app/ui-react/packages/utils/src/autoformHelpers.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx

fixes #270
fixes #286
and some stuff for #304

fix: expose the isInitialValid property and set it appropriately in the editor, add some IDs

---

app/ui-react/packages/api/src/useIntegrationHelpers.tsx
app/ui-react/packages/auto-form/src/AutoForm.tsx
app/ui-react/packages/auto-form/src/FormBuilder.tsx
app/ui-react/packages/auto-form/src/models.ts
app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx
app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx
app/ui-react/packages/utils/src/autoformHelpers.ts
app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx

Was quicker to fix this than write up a bug.  With the required field indicated in place I thought it'd be good to take it a little further and show the required field prompt per a lot of designs and pf guidelines.  So now this:
Shows up as:
and when there's a mix:
also adds a fix for #316

feat: update required field prompts for auto forms

---

app/ui-react/syndesis/package.json
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
app/ui-react/syndesis/src/modules/integrations/resolvers.ts
app/ui-react/syndesis/src/shared/WithLeaveConfirmation.tsx
app/ui-react/typings/allpro__react-router-pause/index.d.ts
app/ui-react/typings/allpro__react-router-pause/package.json
app/ui-react/yarn.lock

This adds a reusable component `WithLeaveConfirmation` that can be used to protect a page/section from navigating away. 
In the integration editor, it's used by setting the `shouldDisplayDialog` property to a function that checks if the following URL is outside the "mountpoint" of the editor.

feat: add navigating away confirmation when in the integration editor

---

.circleci/config.yml
app/ui-react/packages/models/src/extra.d.ts
app/ui-react/packages/ui/src/Connection/ConnectionSkeleton.tsx
app/ui-react/packages/ui/src/Connection/ConnectionsListView.tsx
app/ui-react/packages/ui/src/Customization/ApiConnectorListSkeleton.tsx
app/ui-react/packages/ui/src/Customization/ExtensionListSkeleton.tsx
app/ui-react/packages/ui/src/Integration/IntegrationsListSkeleton.tsx
app/ui-react/packages/ui/src/Layout/PageLoader.tsx
app/ui-react/packages/ui/src/Layout/index.ts
app/ui-react/packages/ui/src/index.css
app/ui-react/syndesis/src/index.tsx
app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
app/ui-react/syndesis/src/modules/extensions/pages/ExtensionDetailsPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailNavBar.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPage.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
app/ui-react/syndesis/src/modules/support/pages/SupportPage.tsx

* Replaced `Loaders` when used as page loaders with the new `PageLoader` one.
* Fixed the connections skeleton loader and tweaked the others.
* Makes use of the integration skeleton loader for the oauth page too (fix #225).
* Restored the integration state passing in the integration detail page.

fix: fix loaders and random stuff

---

app/ui-react/packages/auto-form/src/FormBuilder.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/utils.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx

This flow was giving an error on Atlasmap: new integration -> sql query -> sql stored procedure -> add data mapper step in between the two.

fix: address the data mapper page error when adding a map on newly created integrations

---

app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json

Changes:
- Check and hide ability to delete if step is API provider or CBR
- Move most logic to `AddStepPage` for ease of use with history
Outstanding:
- Check for first and last step of integration flow, on confirmation of delete redirect the user to that position step select page. The check works fine, but the redirect does not. See comments below.
fix #308

308 conditional delete integration editor

---

app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts

This fixes a bug when replacing the end step, where the wrong connections would be displayed.

fix: properly filter the displayed steps based on the current position

---

app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
app/ui-react/packages/ui/src/Shared/ListViewToolbar.css
app/ui-react/packages/ui/src/Shared/ListViewToolbar.tsx

Aligns `<ListViewToolbar>` inside with the list row content below it.
Italicizes note text at the bottom of integration import drag 'n drop box

fix(listviewtoolbar): decrease left/right padding so it aligns with list view content

---

tools/bin/commands/ui

Just a quick tweak for now, with this change you can do `export BACKEND=https://syndesis-staging-2.b6ff.rh-idev.openshiftapps.com` and then `syndesis ui --serve` will point to the second staging backend.

fix: let the staging URL be overridden via environment varible

---

app/ui-react/packages/ui/src/Connection/ConnectionCard.css
app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
app/ui-react/packages/ui/src/Shared/PfDropdownItem.tsx
app/ui-react/packages/ui/stories/Connection/ConnectionDetailsForm.stories.tsx

- See #208
- `ConnectionCard` now uses PF4 Dropdown
- Fixes a regression bug in `ConnectionDetailsForm` that kept the cancel and save buttons always visible
- Added property to `PfDropdownItem` that indicates if item should be disabled
- Added a `ConnectionDetailsForm` story

The connections list page's disabled 'delete' menu item no longer triggers a delete confirmation

---

app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailEditableName.css
app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailEditableName.tsx
app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListViewItem.tsx
app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.css
app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
app/ui-react/packages/ui/src/Integration/IntegrationStatusDetail.css
app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
app/ui-react/packages/ui/src/Shared/ProgressWithLink.css
app/ui-react/packages/ui/src/Shared/ProgressWithLink.tsx
app/ui-react/syndesis/src/modules/integrations/components/TagIntegrationDialogWrapper.css
app/ui-react/syndesis/src/modules/integrations/components/TagIntegrationDialogWrapper.tsx

* removes shield icon from last processed card in integration detail metrics
* adds padding under description paragraph in manage ci/cd dialog in integration details
* removes unnecessary `additionalInfo` value in integration details history table, allowing "last published on date, time" line to be on a single line.
* aligns integration name and published status icon/text in integration details view
* fix the integration progress with link layout

fix(integrationdetails): various ui fixes

---

app/ui-react/packages/auto-form/src/utils.ts

It was from my changes to avoid giving `undefined` values to formik to suppress it's errors about changing controls from controlled to uncontrolled.
fixes #385

fix: make defaultValue work again

---

app/ui-react/packages/api/src/WithSteps.tsx
app/ui-react/packages/api/src/helpers/integrationFunctions.ts
app/ui-react/packages/api/src/useIntegrationHelpers.tsx
app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorForm.tsx
app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json

We were missing a call to the API that fetches the updated descriptor for steps, now we have that.
This fixes - together with some other changes - the steps we display in the editor.
Steps to reproduce:
1. new integration: select * from todo > log
2. add split step in between
3. add a step after the split, basic filter should now show up (it wasn't showing up before)
Also actions like adding/updating/removing steps are all now async, so we show the right spinners where we should.

fix: show the right steps in the editor

---

app/ui-react/packages/ui/src/Dashboard/UptimeMetric.css
app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.css
app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx

The uptime text was ~9px which is inaccessible. Bumping it to 11px.

fix(integration): increase uptime metric text size

---

app/ui-react/packages/api/src/useApiConnector.tsx
app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
app/ui-react/syndesis/src/modules/apiClientConnectors/resolvers.ts

NOTE: Need to address displaying and validating the form with UXD and BE for when a user provides more than one OAuth 2.0 security type. Will be opening up a separate issue for this to explain in greater detail.

API client connector wizard additional work

---

app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts

Fix for issue ENTESB-10723 - also handle case where the view name is escaped with "

Fix for escaped view names

---

app/ui-react/packages/ui/src/Layout/AppLayout.tsx
app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
app/ui-react/packages/ui/src/index.css
app/ui-react/packages/ui/stories/Shared/HelpDropdown.stories.tsx

This PR applies further adjustments to the user/help dropdown menus. We now get the proper "help" icon on large viewports, which converts to a kebab on smaller viewports.
Desktop:
Tablet:
Mobile:

chore(ux): use appropriate icon for help dropdown

---

app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorCreatorLayout.tsx
app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportReview.css
app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportReview.tsx
app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.css
app/ui-react/packages/ui/src/index.css

fixes https://github.com/syndesisio/syndesis-react/issues/401
* fix integration-editor-layout in mobile view (see original problem in screenshots in #401)
* fix mobile wizard steps/toggle/menu in mobile view
* redo extension import review UI
wizard before:
wizard after: 
extension import review before:
after:

fix(ui): fix integration editor layout, wizard ui

---

app/ui-react/packages/api/src/WithSteps.tsx
app/ui-react/packages/models/src/extra.d.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts

fixes syndesisio/syndesis#5492
Also refactors the `StepKind` visible function to be an array of functions to allow for applying multiple conditions that must all be true for a step to be visible.

feat: disallow nested conditional flow steps

---

app/ui-react/packages/ui/src/Integration/Details/IntegrationExposedURL.tsx
app/ui-react/packages/ui/src/Integration/Details/index.ts
app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx

fixes syndesisio/syndesis#5575
@seanforyou23 FYI worked for me on firefox

fix: add the exposed URL if available to the detail page

---

app/ui-react/packages/ui/package.json
app/ui-react/packages/ui/src/Layout/AppLayout.tsx
app/ui-react/packages/ui/src/Layout/WizardSteps.css
app/ui-react/packages/ui/src/Layout/WizardSteps.tsx
app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
app/ui-react/packages/ui/stories/Shared/HelpDropdown.stories.tsx
app/ui-react/yarn.lock

This PR updates the header to more seamlessly collapse/consolidate the user menu at smaller viewports. Previously we would collapse logout into the help menu (keeping the help icon) and later convert that icon to kebab. After further reviewing this interaction, we realized it seems strange and a better experience is to convert the icon to a kebab at the same time we move/consolidate the two menus.
Also fixes a bug where selecting the collapse "toggle" icon for wizard  wasn't actually collapsing the menu. Now it does.
One question that came up along the way was "how are we achieving this collapse functionality for the PF3 Wiz steps?". I don't see this capability in the PF3 react implementation;
http://patternfly-react.surge.sh/patternfly-3/index.html?selectedKind=patternfly-react%2FCommunic …

fix(wiz-toggle): fix wizard toggle icon click-ability

---

app/ui-react/packages/api/src/useConnectorCredentials.tsx
app/ui-react/syndesis/public/oauth-redirect.html
app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
app/ui-react/syndesis/src/modules/connections/resolvers.ts

We need to destroy the state received from backend on API call to `/api/v1/connectors/{id}/credentials` in order for it not to overwrite the cookie received on `/api/v1/credentials/callback`. This eliminates the need to parse the cookie in `oauth-redirect.html` and pass/store it in the app.

fix: don't reset OAuth client state

---

app/ui-react/packages/api/src/WithSteps.tsx
app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx

Bug reported [here](https://github.com/syndesisio/syndesis/issues/5622#issuecomment-500343788).
(oh also fixes a bug with the integration list item that was causing a lot of console errors to be logged)

fix: template step requires an output data shape to be selected

---

app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/mustache-mode-lint.ts

* CodeMirror editor starts at line 0 (due to array index) so need to
increment in order to display correct line number to user.
* This only affects the mustache lint as both velocity and freemarker
already deal with this internally.

fix(5273): Mustache errors showing wrong line number

---

app/ui-react/syndesis/src/modules/integrations/components/WithIntegrationActions.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPage.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx

- see issue syndesisio/syndesis#5578
- added WithRouter to WithIntegrationActions
- after a successful delete, the integrations list page is displayed

Fixes an issue when deleting an integration from it's detail page

---

app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx

Added validate method on the SqlClient form.  Its purpose is to reset the query results table upon change of one of the controls.

TTOOLS-651 Clear query results on form change

---

app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.css
app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.tsx
app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
app/ui-react/packages/ui/src/Integration/IntegrationsListItemBasic.tsx
app/ui-react/packages/ui/src/index.css
app/ui-react/syndesis/src/app/UI.tsx
app/ui-react/syndesis/src/modules/support/components/SelectiveIntegrationList.tsx

This PR truncates long integration names onto a single line using an ellipsis to indicate more content. It also removes the avatar from the header as profile images are not currently a feature we offer. Lastly, it removes the pause icon for stopped integrations from the integration details page.
The treatment of long integration names here is in line with patternfly 3 standards. An upcoming milestone will be to convert innermost components to use patternfly 4, which would be a good time to re-think the design of the overflowing integration names. I point that out because one of the options we've entertained was to show the first two lines of the integration name instead of a single line, but it's not simple to pull off implementation wise and it would be better to research out options …

chore(ux): remove avatar and stopped status icon, truncate long titles

---

app/ui-react/packages/api/src/useApiProviderSummary.tsx
app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.tsx
app/ui-react/packages/ui/src/Integration/OperationsDropdown.css
app/ui-react/packages/ui/src/Integration/OperationsDropdown.tsx
app/ui-react/packages/ui/src/Layout/Breadcrumb.tsx
app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
app/ui-react/syndesis/src/modules/integrations/resolvers.ts

Partially fixes https://github.com/syndesisio/syndesis/issues/5697
Partially fixes https://github.com/syndesisio/syndesis/issues/5600
Fixes https://github.com/syndesisio/syndesis/issues/5675
Fixes https://github.com/syndesisio/syndesis-react/issues/397
Since the spec is returned by an API, every time you go to the API definition you get the one relative to the last saved version of the integration. 
So if edit the definition, change your mind and try to edit it again, you'll lose the previous changes.
Also, this will completely delete whatever was present on the integration before the change in the spec. @zregvart can you confirm this is right?

fix: api provider bugs

---

app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/DescribeDataShapePage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts

fixes #382
Now page 2 of the salesforce configuration looks like it should:
Also I had to finally rename "step" on this particular page to "page", it's been confusing me each time I've been in this code :confused:

fix: ensure any configured properties get passed into the state

---

app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx

Relative issue https://github.com/syndesisio/syndesis/issues/5720

fix: clicking on the about link doesn't change the history anymore

---

app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx

Also, center the card.
Relative issues:
https://github.com/syndesisio/syndesis/issues/5669
https://github.com/syndesisio/syndesis/issues/5670

fix: properly compute the initial validity state in the api connector security page

---

app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts

We should compute the `configuredProperties` in the configuration page since it depends on the mode (adding vs editing) and the page we are currently on.
Relative issue https://github.com/syndesisio/syndesis/issues/5686

fix: properly show the initial value for the form fields in all cases

---

app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx

The card title now shows the action name and the step description.
Relative issue https://github.com/syndesisio/syndesis/issues/5689

fix: better title for the action configuration page

---

app/ui-react/syndesis/src/index.tsx

has nothing to do with https://github.com/syndesisio/syndesis/issues/5732
@seanforyou23 shhh

fix: undo really trivial styling issue that happened, nothing to see here honest
